# 6.1. Beschaffung von Open Data

## 1. Import Biblioteks

In [18]:
import pandas as pd
import os
import glob

## 2. Import data

In [19]:
# Basis-Pfad
base_path = r'C:\Users\faink\Desktop\Achievement_6\02_data'

# Pfade zu Roh- und bereinigten Daten
raw_path = os.path.join(base_path, "1_raw")
cleaned_path = os.path.join(base_path, "2_cleaned")

# Alle CSV-Dateien im Rohdaten-Ordner finden
files = glob.glob(os.path.join(raw_path, "*.csv"))

# Einlesen und Zusammenführen
dfs = [pd.read_csv(f) for f in files]
df = pd.concat(dfs, ignore_index=True)

df.head()

,Country,Region,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),...,Explained by: Freedom to make life choices,Explained by: Generosity,Explained by: Perceptions of corruption,Dystopia + residual,RANK,Happiness score,Whisker-high,Whisker-low,Dystopia (1.83) + residual,Explained by: GDP per capita
0,Switzerland,Western Europe,1.0,7.587,0.03411,1.39651,1.34951,0.94143,0.66557,0.41978,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Iceland,Western Europe,2.0,7.561,0.04884,1.30232,1.40223,0.94784,0.62877,0.14145,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Denmark,Western Europe,3.0,7.527,0.03328,1.32548,1.36058,0.87464,0.64938,0.48357,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Norway,Western Europe,4.0,7.522,0.03880,1.45900,1.33095,0.88521,0.66973,0.36503,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Canada,North America,5.0,7.427,0.03553,1.32629,1.32261,0.90563,0.63297,0.32957,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Die NaN‑Werte entstehen hauptsächlich dadurch, dass der World Happiness Report in verschiedenen Jahren unterschiedliche Variablen verwendet.
Daher handelt es sich nicht um echte fehlende Werte, sondern um strukturelle Unterschiede zwischen den Jahresdateien.
Eine Imputation (z. B. Median oder Mittelwert) wäre in diesem Fall nicht sinnvoll, da sie künstliche Werte erzeugen würde.
Stattdessen wurden nur die Variablen ausgewählt, die in allen Jahren konsistent vorhanden sind.

## 3. Überprüfung der Strukturen

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1231 entries, 0 to 1230
Data columns (total 51 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Country                                     617 non-null    object
 1   Region                                      315 non-null    object
 2   Happiness Rank                              315 non-null    float64
 3   Happiness Score                             315 non-null    float64
 4   Standard Error                              158 non-null    float64
 5   Economy (GDP per Capita)                    315 non-null    float64
 6   Family                                      470 non-null    float64
 7   Health (Life Expectancy)                    315 non-null    float64
 8   Freedom                                     470 non-null    float64
 9   Trust (Government Corruption)               315 non-null    float64
 10  Generosity                                  1084 non-null   float64
 11  Dystopia Residual                           315 non-null    float64
 12  Lower Confidence Interval                   157 non-null    float64
 13  Upper Confidence Interval                   157 non-null    float64
 14  Happiness.Rank                              155 non-null    float64
 15  Happiness.Score                             155 non-null    float64
 16  Whisker.high                                155 non-null    float64
 17  Whisker.low                                 155 non-null    float64
 18  Economy..GDP.per.Capita.                    155 non-null    float64
 19  Health..Life.Expectancy.                    155 non-null    float64
 20  Trust..Government.Corruption.               155 non-null    float64
 21  Dystopia.Residual                           155 non-null    float64
 22  Overall rank                                312 non-null    float64
 23  Country or region                           312 non-null    object
 24  Score                                       312 non-null    float64
 25  GDP per capita                              312 non-null    float64
 26  Social support                              614 non-null    float64
 27  Healthy life expectancy                     614 non-null    float64
 28  Freedom to make life choices                614 non-null    float64
 29  Perceptions of corruption                   613 non-null    float64
 30  Country name                                302 non-null    object
 31  Regional indicator                          302 non-null    object
 32  Ladder score                                302 non-null    float64
 33  Standard error of ladder score              302 non-null    float64
 34  upperwhisker                                302 non-null    float64
 35  lowerwhisker                                302 non-null    float64
 36  Logged GDP per capita                       302 non-null    float64
 37  Ladder score in Dystopia                    302 non-null    float64
 38  Explained by: Log GDP per capita            302 non-null    float64
 39  Explained by: Social support                448 non-null    object
 40  Explained by: Healthy life expectancy       448 non-null    object
 41  Explained by: Freedom to make life choices  448 non-null    object
 42  Explained by: Generosity                    448 non-null    object
 43  Explained by: Perceptions of corruption     448 non-null    object
 44  Dystopia + residual                         302 non-null    float64
 45  RANK                                        147 non-null    float64
 46  Happiness score                             146 non-null    object
 47  Whisker-high                                146 non-null    object
 48  Whisker-low                                 146 non-null    object
 49  Dystopia (1.83) + residual                  146 non-null    object
 50  Explained by: GDP per capita                146 non-null    object
dtypes: float64(36), object(15)
memory usage: 490.6+ KB

In [4]:
df.describe ()

,Happiness Rank,Happiness Score,Standard Error,Economy (GDP per Capita),Family,Health (Life Expectancy),Freedom,Trust (Government Corruption),Generosity,Dystopia Residual,...,Perceptions of corruption,Ladder score,Standard error of ladder score,upperwhisker,lowerwhisker,Logged GDP per capita,Ladder score in Dystopia,Explained by: Log GDP per capita,Dystopia + residual,RANK
count,315.000000,315.000000,158.000000,315.000000,470.000000,315.000000,470.000000,315.000000,1084.000000,315.000000,...,613.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,302.000000,147.000000
mean,79.238095,5.378949,0.047885,0.899837,0.990347,0.594054,0.402828,0.140532,0.153545,2.212032,...,0.416267,5.502645,0.056111,5.612629,5.392641,9.363053,2.198127,0.922248,2.198290,74.000000
std,45.538922,1.141531,0.017146,0.410780,0.318707,0.240790,0.150356,0.115490,0.167592,0.558728,...,0.340490,1.092111,0.020292,1.074850,1.110534,1.180595,0.229201,0.391830,0.595958,42.579338
min,1.000000,2.839000,0.018480,0.000000,0.000000,0.000000,0.000000,0.000000,-0.300907,0.328580,...,0.000000,2.523000,0.025902,2.596000,2.449000,6.492642,1.972317,0.000000,0.257241,1.000000
25%,40.000000,4.510000,0.037268,0.594900,0.793000,0.419645,0.297615,0.061315,0.064828,1.884135,...,0.082000,4.769400,0.042000,4.885588,4.636008,8.483295,1.972317,0.633963,1.823000,37.500000
50%,79.000000,5.286000,0.043940,0.973060,1.025665,0.640450,0.418347,0.106130,0.162140,2.211260,...,0.306000,5.524500,0.052321,5.610132,5.426829,9.514612,1.972317,0.982509,2.223108,74.000000
75%,118.500000,6.269000,0.052300,1.229000,1.228745,0.787640,0.516850,0.178610,0.252000,2.563470,...,0.780623,6.248375,0.066000,6.362124,6.136381,10.356000,2.430000,1.241988,2.619750,110.500000
max,158.000000,7.587000,0.136930,1.824270,1.610574,1.025250,0.669730,0.551910,0.838075,3.837720,...,0.939000,7.842000,0.173000,7.904000,7.780000,11.647000,2.430000,1.751000,3.482000,147.000000

## 5. Vereinheitlichung der Namen der Spalten

In [21]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [22]:
# Entfernung Dublicates der Spalten

df = df.loc[:, ~df.columns.duplicated()]

## 6. Überprüfung auf fehlende Werte

In [7]:
df.isna().sum()

country                                        614
region                                         916
happiness_rank                                 916
happiness_score                                916
standard_error                                1073
economy_(gdp_per_capita)                       916
family                                         761
health_(life_expectancy)                       916
freedom                                        761
trust_(government_corruption)                  916
generosity                                     147
dystopia_residual                              916
lower_confidence_interval                     1074
upper_confidence_interval                     1074
happiness.rank                                1076
happiness.score                               1076
whisker.high                                  1076
whisker.low                                   1076
economy..gdp.per.capita.                      1076
health..life.expectancy.                      1076
trust..government.corruption.                 1076
dystopia.residual                             1076
overall_rank                                   919
country_or_region                              919
score                                          919
gdp_per_capita                                 919
social_support                                 617
healthy_life_expectancy                        617
freedom_to_make_life_choices                   617
perceptions_of_corruption                      618
country_name                                   929
regional_indicator                             929
ladder_score                                   929
standard_error_of_ladder_score                 929
upperwhisker                                   929
lowerwhisker                                   929
logged_gdp_per_capita                          929
ladder_score_in_dystopia                       929
explained_by:_log_gdp_per_capita               929
explained_by:_social_support                   783
explained_by:_healthy_life_expectancy          783
explained_by:_freedom_to_make_life_choices     783
explained_by:_generosity                       783
explained_by:_perceptions_of_corruption        783
dystopia_+_residual                            929
rank                                          1084
whisker-high                                  1085
whisker-low                                   1085
dystopia_(1.83)_+_residual                    1085
explained_by:_gdp_per_capita                  1085
dtype: int64

## 7. Zusammenführung aller „Versionen“ einer Variablen zu einer einzigen

Auswahl konsistenter Variablen:
Beim Zusammenführen der Jahresdateien zeigte sich, dass viele Variablen je nach Jahr unterschiedliche Namen oder Strukturen aufweisen.
Um einen konsistenten, vergleichbaren und modellierbaren Datensatz zu erhalten, wurden nur jene Variablen beibehalten, die in allen Jahren vorhanden sind und inhaltlich dieselben Konzepte abbilden.
Dadurch werden strukturelle NaN‑Werte vermieden und eine saubere Grundlage für Regression, Clustering und die spätere Dashboard‑Erstellung geschaffen.

In [ ]:
### 7.1. Erstellung eine Funktion zum Zusammenführen von Spalten

In [23]:
def merge_columns(df, col_list):
    series = None
    for col in col_list:
        if col in df.columns:
            if series is None:
                series = df[col].copy()
            else:
                series = series.fillna(df[col])
    return series

In [ ]:
### 7.2 Vereinigung von Spalten

In [24]:
# Überprüfung der Namen

df.columns

Index(['country', 'region', 'happiness_rank', 'happiness_score',
       'standard_error', 'economy_(gdp_per_capita)', 'family',
       'health_(life_expectancy)', 'freedom', 'trust_(government_corruption)',
       'generosity', 'dystopia_residual', 'lower_confidence_interval',
       'upper_confidence_interval', 'happiness.rank', 'happiness.score',
       'whisker.high', 'whisker.low', 'economy..gdp.per.capita.',
       'health..life.expectancy.', 'trust..government.corruption.',
       'dystopia.residual', 'overall_rank', 'country_or_region', 'score',
       'gdp_per_capita', 'social_support', 'healthy_life_expectancy',
       'freedom_to_make_life_choices', 'perceptions_of_corruption',
       'country_name', 'regional_indicator', 'ladder_score',
       'standard_error_of_ladder_score', 'upperwhisker', 'lowerwhisker',
       'logged_gdp_per_capita', 'ladder_score_in_dystopia',
       'explained_by:_log_gdp_per_capita', 'explained_by:_social_support',
       'explained_by:_healthy_life_expectancy',
       'explained_by:_freedom_to_make_life_choices',
       'explained_by:_generosity', 'explained_by:_perceptions_of_corruption',
       'dystopia_+_residual', 'rank', 'whisker-high', 'whisker-low',
       'dystopia_(1.83)_+_residual', 'explained_by:_gdp_per_capita'],
      dtype='object')

In [25]:
# Land

df["country_final"] = merge_columns(df, [
    "country",
    "country_or_region",
    "country_name"
])

In [26]:
# Region

df["region_final"] = merge_columns(df, [
    "regional_indicator",
    "region"
])

In [27]:
[col for col in df.columns if "happiness" in col]

['happiness_rank', 'happiness_score', 'happiness.rank', 'happiness.score']

In [28]:
# Happiness Score

df["happiness_final"] = merge_columns(df, [
    "ladder_score",
    "happiness_score",
    "score",
    "happiness.score"
])

In [34]:
# GDR

df["gdp_final"] = merge_columns(df, [
    "gdp_per_capita",
    "economy_(gdp_per_capita)",
    "economy..gdp.per.capita.",
    "logged_gdp_per_capita",
    "explained_by:_log_gdp_per_capita",
    "explained_by:_gdp_per_capita"
])

In [36]:
# Gesundheit

df["health_final"] = merge_columns(df, [
    "health_(life_expectancy)",
    "health..life.expectancy.",
    "health..life.expectancy"
    "explained_by:_healthy_life_expectancy"

])

In [37]:
# Social Support

df["social_support_final"] = merge_columns(df, [
    "family",
    "social_support",
    "explained_by:_social_support"
])

In [38]:
# Freiheit

df["freedom_final"] = merge_columns(df, [
    "freedom_to_make_life_choices",
    "freedom",
    "explained_by:_freedom_to_make_life_choices"
])

In [39]:
# Corruption

df["corruption_final"] = merge_columns(df, [
    "perceptions_of_corruption",
    "trust_(government_corruption)",
    "trust..government.corruption.",
    "explained_by:_perceptions_of_corruption"
])

### 7.3. Finaly Datensatz

In [40]:
columns_to_keep = [
    "country_final",
    "region_final",
    "happiness_final",
    "gdp_final",
    "social_support",
    "health_final",
    "freedom_final",
    "generosity",
    "corruption_final"
]

df_clean = df[columns_to_keep].copy()

In [94]:
# Überprüfung

df_clean.shape
df_clean.isna().sum()
df_clean.head()

,country_final,region_final,happiness_final,gdp_final,social_support,health_final,freedom_final,generosity,corruption_final
0,Switzerland,Western Europe,7.587,1.39651,NaN,0.94143,0.66557,0.29678,0.41978
1,Iceland,Western Europe,7.561,1.30232,NaN,0.94784,0.62877,0.43630,0.14145
2,Denmark,Western Europe,7.527,1.32548,NaN,0.87464,0.64938,0.34139,0.48357
3,Norway,Western Europe,7.522,1.45900,NaN,0.88521,0.66973,0.34699,0.36503
4,Canada,North America,7.427,1.32629,NaN,0.90563,0.63297,0.45811,0.32957

## 8. Duplikate entfernen

In [41]:
df_clean = df_clean.drop_duplicates()

## 9. Überprüfung der geografischen Variablen

In [42]:
df_clean['country_final'].nunique()

196

In [46]:
print(df_clean['country_final'].tolist())

['Switzerland', 'Iceland', 'Denmark', 'Norway', 'Canada', 'Finland', 'Netherlands', 'Sweden', 'New Zealand', 'Australia', 'Israel', 'Costa Rica', 'Austria', 'Mexico', 'United States', 'Brazil', 'Luxembourg', 'Ireland', 'Belgium', 'United Arab Emirates', 'United Kingdom', 'Oman', 'Venezuela', 'Singapore', 'Panama', 'Germany', 'Chile', 'Qatar', 'France', 'Argentina', 'Czech Republic', 'Uruguay', 'Colombia', 'Thailand', 'Saudi Arabia', 'Spain', 'Malta', 'Taiwan', 'Kuwait', 'Suriname', 'Trinidad and Tobago', 'El Salvador', 'Guatemala', 'Uzbekistan', 'Slovakia', 'Japan', 'South Korea', 'Ecuador', 'Bahrain', 'Italy', 'Bolivia', 'Moldova', 'Paraguay', 'Kazakhstan', 'Slovenia', 'Lithuania', 'Nicaragua', 'Peru', 'Belarus', 'Poland', 'Malaysia', 'Croatia', 'Libya', 'Russia', 'Jamaica', 'North Cyprus', 'Cyprus', 'Algeria', 'Kosovo', 'Turkmenistan', 'Mauritius', 'Hong Kong', 'Estonia', 'Indonesia', 'Vietnam', 'Turkey', 'Kyrgyzstan', 'Nigeria', 'Bhutan', 'Azerbaijan', 'Pakistan', 'Jordan', 'Montenegro', 'China', 'Zambia', 'Romania', 'Serbia', 'Portugal', 'Latvia', 'Philippines', 'Somaliland region', 'Morocco', 'Macedonia', 'Mozambique', 'Albania', 'Bosnia and Herzegovina', 'Lesotho', 'Dominican Republic', 'Laos', 'Mongolia', 'Swaziland', 'Greece', 'Lebanon', 'Hungary', 'Honduras', 'Tajikistan', 'Tunisia', 'Palestinian Territories', 'Bangladesh', 'Iran', 'Ukraine', 'Iraq', 'South Africa', 'Ghana', 'Zimbabwe', 'Liberia', 'India', 'Sudan', 'Haiti', 'Congo (Kinshasa)', 'Nepal', 'Ethiopia', 'Sierra Leone', 'Mauritania', 'Kenya', 'Djibouti', 'Armenia', 'Botswana', 'Myanmar', 'Georgia', 'Malawi', 'Sri Lanka', 'Cameroon', 'Bulgaria', 'Egypt', 'Yemen', 'Angola', 'Mali', 'Congo (Brazzaville)', 'Comoros', 'Uganda', 'Senegal', 'Gabon', 'Niger', 'Cambodia', 'Tanzania', 'Madagascar', 'Central African Republic', 'Chad', 'Guinea', 'Ivory Coast', 'Burkina Faso', 'Afghanistan', 'Rwanda', 'Benin', 'Syria', 'Burundi', 'Togo', 'Denmark', 'Switzerland', 'Iceland', 'Norway', 'Finland', 'Canada', 'Netherlands', 'New Zealand', 'Australia', 'Sweden', 'Israel', 'Austria', 'United States', 'Costa Rica', 'Puerto Rico', 'Germany', 'Brazil', 'Belgium', 'Ireland', 'Luxembourg', 'Mexico', 'Singapore', 'United Kingdom', 'Chile', 'Panama', 'Argentina', 'Czech Republic', 'United Arab Emirates', 'Uruguay', 'Malta', 'Colombia', 'France', 'Thailand', 'Saudi Arabia', 'Taiwan', 'Qatar', 'Spain', 'Algeria', 'Guatemala', 'Suriname', 'Kuwait', 'Bahrain', 'Trinidad and Tobago', 'Venezuela', 'Slovakia', 'El Salvador', 'Malaysia', 'Nicaragua', 'Uzbekistan', 'Italy', 'Ecuador', 'Belize', 'Japan', 'Kazakhstan', 'Moldova', 'Russia', 'Poland', 'South Korea', 'Bolivia', 'Lithuania', 'Belarus', 'North Cyprus', 'Slovenia', 'Peru', 'Turkmenistan', 'Mauritius', 'Libya', 'Latvia', 'Cyprus', 'Paraguay', 'Romania', 'Estonia', 'Jamaica', 'Croatia', 'Hong Kong', 'Somalia', 'Kosovo', 'Turkey', 'Indonesia', 'Jordan', 'Azerbaijan', 'Philippines', 'China', 'Bhutan', 'Kyrgyzstan', 'Serbia', 'Bosnia and Herzegovina', 'Montenegro', 'Dominican Republic', 'Morocco', 'Hungary', 'Pakistan', 'Lebanon', 'Portugal', 'Macedonia', 'Vietnam', 'Somaliland Region', 'Tunisia', 'Greece', 'Tajikistan', 'Mongolia', 'Laos', 'Nigeria', 'Honduras', 'Iran', 'Zambia', 'Nepal', 'Palestinian Territories', 'Albania', 'Bangladesh', 'Sierra Leone', 'Iraq', 'Namibia', 'Cameroon', 'Ethiopia', 'South Africa', 'Sri Lanka', 'India', 'Myanmar', 'Egypt', 'Armenia', 'Kenya', 'Ukraine', 'Ghana', 'Congo (Kinshasa)', 'Georgia', 'Congo (Brazzaville)', 'Senegal', 'Bulgaria', 'Mauritania', 'Zimbabwe', 'Malawi', 'Sudan', 'Gabon', 'Mali', 'Haiti', 'Botswana', 'Comoros', 'Ivory Coast', 'Cambodia', 'Angola', 'Niger', 'South Sudan', 'Chad', 'Burkina Faso', 'Uganda', 'Yemen', 'Madagascar', 'Tanzania', 'Liberia', 'Guinea', 'Rwanda', 'Benin', 'Afghanistan', 'Togo', 'Syria', 'Burundi', 'Norway', 'Denmark', 'Iceland', 'Switzerland', 'Finland', 'Netherlands', 'Canada', 'New Zealand', 'Sweden', 'Australia', 'Israel', 'Costa Rica', 'Austria', 'United States', 'Ireland', 'Germany', 'Belgium', 'Luxembourg', 'United Kingdom', 'Chile', 'United Arab Emirates', 'Brazil', 'Czech Republic', 'Argentina', 'Mexico', 'Singapore', 'Malta', 'Uruguay', 'Guatemala', 'Panama', 'France', 'Thailand', 'Taiwan Province of China', 'Spain', 'Qatar', 'Colombia', 'Saudi Arabia', 'Trinidad and Tobago', 'Kuwait', 'Slovakia', 'Bahrain', 'Malaysia', 'Nicaragua', 'Ecuador', 'El Salvador', 'Poland', 'Uzbekistan', 'Italy', 'Russia', 'Belize', 'Japan', 'Lithuania', 'Algeria', 'Latvia', 'South Korea', 'Moldova', 'Romania', 'Bolivia', 'Turkmenistan', 'Kazakhstan', 'North Cyprus', 'Slovenia', 'Peru', 'Mauritius', 'Cyprus', 'Estonia', 'Belarus', 'Libya', 'Turkey', 'Paraguay', 'Hong Kong S.A.R., China', 'Philippines', 'Serbia', 'Jordan', 'Hungary', 'Jamaica', 'Croatia', 'Kosovo', 'China', 'Pakistan', 'Indonesia', 'Venezuela', 'Montenegro', 'Morocco', 'Azerbaijan', 'Dominican Republic', 'Greece', 'Lebanon', 'Portugal', 'Bosnia and Herzegovina', 'Honduras', 'Macedonia', 'Somalia', 'Vietnam', 'Nigeria', 'Tajikistan', 'Bhutan', 'Kyrgyzstan', 'Nepal', 'Mongolia', 'South Africa', 'Tunisia', 'Palestinian Territories', 'Egypt', 'Bulgaria', 'Sierra Leone', 'Cameroon', 'Iran', 'Albania', 'Bangladesh', 'Namibia', 'Kenya', 'Mozambique', 'Myanmar', 'Senegal', 'Zambia', 'Iraq', 'Gabon', 'Ethiopia', 'Sri Lanka', 'Armenia', 'India', 'Mauritania', 'Congo (Brazzaville)', 'Georgia', 'Congo (Kinshasa)', 'Mali', 'Ivory Coast', 'Cambodia', 'Sudan', 'Ghana', 'Ukraine', 'Uganda', 'Burkina Faso', 'Niger', 'Malawi', 'Chad', 'Zimbabwe', 'Lesotho', 'Angola', 'Afghanistan', 'Botswana', 'Benin', 'Madagascar', 'Haiti', 'Yemen', 'South Sudan', 'Liberia', 'Guinea', 'Togo', 'Rwanda', 'Syria', 'Tanzania', 'Burundi', 'Central African Republic', 'Finland', 'Norway', 'Denmark', 'Iceland', 'Switzerland', 'Netherlands', 'Canada', 'New Zealand', 'Sweden', 'Australia', 'United Kingdom', 'Austria', 'Costa Rica', 'Ireland', 'Germany', 'Belgium', 'Luxembourg', 'United States', 'Israel', 'United Arab Emirates', 'Czech Republic', 'Malta', 'France', 'Mexico', 'Chile', 'Taiwan', 'Panama', 'Brazil', 'Argentina', 'Guatemala', 'Uruguay', 'Qatar', 'Saudi Arabia', 'Singapore', 'Malaysia', 'Spain', 'Colombia', 'Trinidad & Tobago', 'Slovakia', 'El Salvador', 'Nicaragua', 'Poland', 'Bahrain', 'Uzbekistan', 'Kuwait', 'Thailand', 'Italy', 'Ecuador', 'Belize', 'Lithuania', 'Slovenia', 'Romania', 'Latvia', 'Japan', 'Mauritius', 'Jamaica', 'South Korea', 'Northern Cyprus', 'Russia', 'Kazakhstan', 'Cyprus', 'Bolivia', 'Estonia', 'Paraguay', 'Peru', 'Kosovo', 'Moldova', 'Turkmenistan', 'Hungary', 'Libya', 'Philippines', 'Honduras', 'Belarus', 'Turkey', 'Pakistan', 'Hong Kong', 'Portugal', 'Serbia', 'Greece', 'Lebanon', 'Montenegro', 'Croatia', 'Dominican Republic', 'Algeria', 'Morocco', 'China', 'Azerbaijan', 'Tajikistan', 'Macedonia', 'Jordan', 'Nigeria', 'Kyrgyzstan', 'Bosnia and Herzegovina', 'Mongolia', 'Vietnam', 'Indonesia', 'Bhutan', 'Somalia', 'Cameroon', 'Bulgaria', 'Nepal', 'Venezuela', 'Gabon', 'Palestinian Territories', 'South Africa', 'Iran', 'Ivory Coast', 'Ghana', 'Senegal', 'Laos', 'Tunisia', 'Albania', 'Sierra Leone', 'Congo (Brazzaville)', 'Bangladesh', 'Sri Lanka', 'Iraq', 'Mali', 'Namibia', 'Cambodia', 'Burkina Faso', 'Egypt', 'Mozambique', 'Kenya', 'Zambia', 'Mauritania', 'Ethiopia', 'Georgia', 'Armenia', 'Myanmar', 'Chad', 'Congo (Kinshasa)', 'India', 'Niger', 'Uganda', 'Benin', 'Sudan', 'Ukraine', 'Togo', 'Guinea', 'Lesotho', 'Angola', 'Madagascar', 'Zimbabwe', 'Afghanistan', 'Botswana', 'Malawi', 'Haiti', 'Liberia', 'Syria', 'Rwanda', 'Yemen', 'Tanzania', 'South Sudan', 'Central African Republic', 'Burundi', 'Finland', 'Denmark', 'Norway', 'Iceland', 'Netherlands', 'Switzerland', 'Sweden', 'New Zealand', 'Canada', 'Austria', 'Australia', 'Costa Rica', 'Israel', 'Luxembourg', 'United Kingdom', 'Ireland', 'Germany', 'Belgium', 'United States', 'Czech Republic', 'United Arab Emirates', 'Malta', 'Mexico', 'France', 'Taiwan', 'Chile', 'Guatemala', 'Saudi Arabia', 'Qatar', 'Spain', 'Panama', 'Brazil', 'Uruguay', 'Singapore', 'El Salvador', 'Italy', 'Bahrain', 'Slovakia', 'Trinidad & Tobago', 'Poland', 'Uzbekistan', 'Lithuania', 'Colombia', 'Slovenia', 'Nicaragua', 'Kosovo', 'Argentina', 'Romania', 'Cyprus', 'Ecuador', 'Kuwait', 'Thailand', 'Latvia', 'South Korea', 'Estonia', 'Jamaica', 'Mauritius', 'Japan', 'Honduras', 'Kazakhstan', 'Bolivia', 'Hungary', 'Paraguay', 'Northern Cyprus', 'Peru', 'Portugal', 'Pakistan', 'Russia', 'Philippines', 'Serbia', 'Moldova', 'Libya', 'Montenegro', 'Tajikistan', 'Croatia', 'Hong Kong', 'Dominican Republic', 'Bosnia and Herzegovina', 'Turkey', 'Malaysia', 'Belarus', 'Greece', 'Mongolia', 'North Macedonia', 'Nigeria', 'Kyrgyzstan', 'Turkmenistan', 'Algeria', 'Morocco', 'Azerbaijan', 'Lebanon', 'Indonesia', 'China', 'Vietnam', 'Bhutan', 'Cameroon', 'Bulgaria', 'Ghana', 'Ivory Coast', 'Nepal', 'Jordan', 'Benin', 'Congo (Brazzaville)', 'Gabon', 'Laos', 'South Africa', 'Albania', 'Venezuela', 'Cambodia', 'Palestinian Territories', 'Senegal', 'Somalia', 'Namibia', 'Niger', 'Burkina Faso', 'Armenia', 'Iran', 'Guinea', 'Georgia', 'Gambia', 'Kenya', 'Mauritania', 'Mozambique', 'Tunisia', 'Bangladesh', 'Iraq', 'Congo (Kinshasa)', 'Mali', 'Sierra Leone', 'Sri Lanka', 'Myanmar', 'Chad', 'Ukraine', 'Ethiopia', 'Swaziland', 'Uganda', 'Egypt', 'Zambia', 'Togo', 'India', 'Liberia', 'Comoros', 'Madagascar', 'Lesotho', 'Burundi', 'Zimbabwe', 'Haiti', 'Botswana', 'Syria', 'Malawi', 'Yemen', 'Rwanda', 'Tanzania', 'Afghanistan', 'Central African Republic', 'South Sudan', 'Finland', 'Denmark', 'Switzerland', 'Iceland', 'Norway', 'Netherlands', 'Sweden', 'New Zealand', 'Austria', 'Luxembourg', 'Canada', 'Australia', 'United Kingdom', 'Israel', 'Costa Rica', 'Ireland', 'Germany', 'United States', 'Czech Republic', 'Belgium', 'United Arab Emirates', 'Malta', 'France', 'Mexico', 'Taiwan Province of China', 'Uruguay', 'Saudi Arabia', 'Spain', 'Guatemala', 'Italy', 'Singapore', 'Brazil', 'Slovenia', 'El Salvador', 'Kosovo', 'Panama', 'Slovakia', 'Uzbekistan', 'Chile', 'Bahrain', 'Lithuania', 'Trinidad and Tobago', 'Poland', 'Colombia', 'Cyprus', 'Nicaragua', 'Romania', 'Kuwait', 'Mauritius', 'Kazakhstan', 'Estonia', 'Philippines', 'Hungary', 'Thailand', 'Argentina', 'Honduras', 'Latvia', 'Ecuador', 'Portugal', 'Jamaica', 'South Korea', 'Japan', 'Peru', 'Serbia', 'Bolivia', 'Pakistan', 'Paraguay', 'Dominican Republic', 'Bosnia and Herzegovina', 'Moldova', 'Tajikistan', 'Montenegro', 'Russia', 'Kyrgyzstan', 'Belarus', 'North Cyprus', 'Greece', 'Hong Kong S.A.R. of China', 'Croatia', 'Libya', 'Mongolia', 'Malaysia', 'Vietnam', 'Indonesia', 'Ivory Coast', 'Benin', 'Maldives', 'Congo (Brazzaville)', 'Azerbaijan', 'Macedonia', 'Ghana', 'Nepal', 'Turkey', 'China', 'Turkmenistan', 'Bulgaria', 'Morocco', 'Cameroon', 'Venezuela', 'Algeria', 'Senegal', 'Guinea', 'Niger', 'Laos', 'Albania', 'Cambodia', 'Bangladesh', 'Gabon', 'South Africa', 'Iraq', 'Lebanon', 'Burkina Faso', 'Gambia', 'Mali', 'Nigeria', 'Armenia', 'Georgia', 'Iran', 'Jordan', 'Mozambique', 'Kenya', 'Namibia', 'Ukraine', 'Liberia', 'Palestinian Territories', 'Uganda', 'Chad', 'Tunisia', 'Mauritania', 'Sri Lanka', 'Congo (Kinshasa)', 'Swaziland', 'Myanmar', 'Comoros', 'Togo', 'Ethiopia', 'Madagascar', 'Egypt', 'Sierra Leone', 'Burundi', 'Zambia', 'Haiti', 'Lesotho', 'India', 'Malawi', 'Yemen', 'Botswana', 'Tanzania', 'Central African Republic', 'Rwanda', 'Zimbabwe', 'South Sudan', 'Afghanistan', 'Finland', 'Denmark', 'Switzerland', 'Iceland', 'Netherlands', 'Norway', 'Sweden', 'Luxembourg', 'New Zealand', 'Austria', 'Australia', 'Israel', 'Germany', 'Canada', 'Ireland', 'Costa Rica', 'United Kingdom', 'Czech Republic', 'United States', 'Belgium', 'France', 'Bahrain', 'Malta', 'Taiwan Province of China', 'United Arab Emirates', 'Saudi Arabia', 'Spain', 'Italy', 'Slovenia', 'Guatemala', 'Uruguay', 'Singapore', 'Kosovo', 'Slovakia', 'Brazil', 'Mexico', 'Jamaica', 'Lithuania', 'Cyprus', 'Estonia', 'Panama', 'Uzbekistan', 'Chile', 'Poland', 'Kazakhstan', 'Romania', 'Kuwait', 'Serbia', 'El Salvador', 'Mauritius', 'Latvia', 'Colombia', 'Hungary', 'Thailand', 'Nicaragua', 'Japan', 'Argentina', 'Portugal', 'Honduras', 'Croatia', 'Philippines', 'South Korea', 'Peru', 'Bosnia and Herzegovina', 'Moldova', 'Ecuador', 'Kyrgyzstan', 'Greece', 'Bolivia', 'Mongolia', 'Paraguay', 'Montenegro', 'Dominican Republic', 'North Cyprus', 'Belarus', 'Russia', 'Hong Kong S.A.R. of China', 'Tajikistan', 'Vietnam', 'Libya', 'Malaysia', 'Indonesia', 'Congo (Brazzaville)', 'China', 'Ivory Coast', 'Armenia', 'Nepal', 'Bulgaria', 'Maldives', 'Azerbaijan', 'Cameroon', 'Senegal', 'Albania', 'North Macedonia', 'Ghana', 'Niger', 'Turkmenistan', 'Gambia', 'Benin', 'Laos', 'Bangladesh', 'Guinea', 'South Africa', 'Turkey', 'Pakistan', 'Morocco', 'Venezuela', 'Georgia', 'Algeria', 'Ukraine', 'Iraq', 'Gabon', 'Burkina Faso', 'Cambodia', 'Mozambique', 'Nigeria', 'Mali', 'Iran', 'Uganda', 'Liberia', 'Kenya', 'Tunisia', 'Lebanon', 'Namibia', 'Palestinian Territories', 'Myanmar', 'Jordan', 'Chad', 'Sri Lanka', 'Swaziland', 'Comoros', 'Egypt', 'Ethiopia', 'Mauritania', 'Madagascar', 'Togo', 'Zambia', 'Sierra Leone', 'India', 'Burundi', 'Yemen', 'Tanzania', 'Haiti', 'Malawi', 'Lesotho', 'Botswana', 'Rwanda', 'Zimbabwe', 'Afghanistan', 'Finland', 'Denmark', 'Iceland', 'Switzerland', 'Netherlands', 'Luxembourg*', 'Sweden', 'Norway', 'Israel', 'New Zealand', 'Austria', 'Australia', 'Ireland', 'Germany', 'Canada', 'United States', 'United Kingdom', 'Czechia', 'Belgium', 'France', 'Bahrain', 'Slovenia', 'Costa Rica', 'United Arab Emirates', 'Saudi Arabia', 'Taiwan Province of China', 'Singapore', 'Romania', 'Spain', 'Uruguay', 'Italy', 'Kosovo', 'Malta', 'Lithuania', 'Slovakia', 'Estonia', 'Panama', 'Brazil', 'Guatemala*', 'Kazakhstan', 'Cyprus', 'Latvia', 'Serbia', 'Chile', 'Nicaragua', 'Mexico', 'Croatia', 'Poland', 'El Salvador', 'Kuwait*', 'Hungary', 'Mauritius', 'Uzbekistan', 'Japan', 'Honduras', 'Portugal', 'Argentina', 'Greece', 'South Korea', 'Philippines', 'Thailand', 'Moldova', 'Jamaica', 'Kyrgyzstan', 'Belarus*', 'Colombia', 'Bosnia and Herzegovina', 'Mongolia', 'Dominican Republic', 'Malaysia', 'Bolivia', 'China', 'Paraguay', 'Peru', 'Montenegro', 'Ecuador', 'Vietnam', 'Turkmenistan*', 'North Cyprus*', 'Russia', 'Hong Kong S.A.R. of China', 'Armenia', 'Tajikistan', 'Nepal', 'Bulgaria', 'Libya*', 'Indonesia', 'Ivory Coast', 'North Macedonia', 'Albania', 'South Africa', 'Azerbaijan*', 'Gambia*', 'Bangladesh', 'Laos', 'Algeria', 'Liberia*', 'Ukraine', 'Congo', 'Morocco', 'Mozambique', 'Cameroon', 'Senegal', 'Niger*', 'Georgia', 'Gabon', 'Iraq', 'Venezuela', 'Guinea', 'Iran', 'Ghana', 'Turkey', 'Burkina Faso', 'Cambodia', 'Benin', 'Comoros*', 'Uganda', 'Nigeria', 'Kenya', 'Tunisia', 'Pakistan', 'Palestinian Territories*', 'Mali', 'Namibia', 'Eswatini, Kingdom of*', 'Myanmar', 'Sri Lanka', 'Madagascar*', 'Egypt', 'Chad*', 'Ethiopia', 'Yemen*', 'Mauritania*', 'Jordan', 'Togo', 'India', 'Zambia', 'Malawi', 'Tanzania', 'Sierra Leone', 'Lesotho*', 'Botswana*', 'Rwanda*', 'Zimbabwe', 'Lebanon', 'Afghanistan', 'xx']

## 10. Vereinheitlichung der Ländernamen

In [47]:
df_clean["country_final"] = (
    df_clean["country_final"]
    .astype(str)
    .str.strip()
    .str.replace("*", "", regex=False)
    .str.replace(r"\s+", " ", regex=True)
    .str.replace("&", "and", regex=False)
    .str.title()
)

In [48]:
country_mapping = {
    "Taiwan Province Of China": "Taiwan",
    "Hong Kong S.A.R. Of China": "Hong Kong",
    "Hong Kong S.A.R., China": "Hong Kong",
    "Hong Kong Sar": "Hong Kong",
    "Czechia": "Czech Republic",
    "North Macedonia": "Macedonia",
    "Eswatini, Kingdom Of": "Eswatini",
    "Swaziland": "Eswatini",
    "Trinidad & Tobago": "Trinidad And Tobago",
    "Somaliland Region": "Somaliland",
    "Somaliland": "Somalia",
    "Ivory Coast": "Côte D'Ivoire",
    "Congo (Brazzaville)": "Republic Of The Congo",
    "Congo (Kinshasa)": "Democratic Republic Of The Congo",
    "Congo": "Republic Of The Congo",
    "Gambia*": "Gambia",
    "Guatemala*": "Guatemala",
    "Kuwait*": "Kuwait",
    "Belarus*": "Belarus",
    "Turkmenistan*": "Turkmenistan",
    "North Cyprus*": "North Cyprus",
    "Libya*": "Libya",
    "Comoros*": "Comoros",
    "Niger*": "Niger",
    "Palestinian Territories*": "Palestinian Territories",
    "Madagascar*": "Madagascar",
    "Chad*": "Chad",
    "Yemen*": "Yemen",
    "Mauritania*": "Mauritania",
    "Lesotho*": "Lesotho",
    "Botswana*": "Botswana",
    "Rwanda*": "Rwanda",
    "Eswatini": "Eswatini",
    "Xx": None  # entfernen
}

df_clean["country_final"] = df_clean["country_final"].replace(country_mapping)

In [49]:
df_clean = df_clean[df_clean["country_final"].notna()]
df_clean = df_clean[df_clean["country_final"] != "Xx"]

## 10. Export Rohdaten

In [50]:
df_clean.to_csv(
    os.path.join(cleaned_path, 'cleaned_data.csv'),
    index=False
)